on:
  push:
    tags: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          make a11y-outline.firefox.zip
          make a11y-outline.chromium.zip
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            a11y-outline.firefox.zip
            a11y-outline.chromium.zip
